# Extração MediaPipe — INCLUDE-50

Este notebook faz o fluxo completo:

1. Descobre as classes presentes em `data/raw/include50`.
2. Cria/usa uma lista de 50 classes em `include50_labels.txt`.
3. Extrai landmarks com MediaPipe Holistic.
4. Salva um CSV final em `data/interim/include50/include50_mediapipe.csv`.

**Modo fácil:** se `include50_labels.txt` não existir, o notebook cria uma seleção provisória de 50 classes de forma automática e salva o arquivo.

In [10]:
from pathlib import Path
import re
import hashlib
import warnings
from typing import List, Dict, Optional

import numpy as np
import pandas as pd

# ========= CONFIGURAÇÃO PRINCIPAL =========

PROJECT_ROOT = Path.cwd().parent

RAW_ROOT = PROJECT_ROOT / "data/raw/include50"
OUTPUT_DIR = PROJECT_ROOT / "data/interim/include50"

LABELS_PATH = RAW_ROOT / "include50_labels.txt"
INVENTORY_PATH = OUTPUT_DIR / "include50_discovered_classes.csv"
SELECTED_CLASSES_PATH = OUTPUT_DIR / "include50_selected_classes.csv"
FINAL_CSV_PATH = OUTPUT_DIR / "include50_mediapipe.csv"
SHARDS_DIR = OUTPUT_DIR / "shards"

VIDEO_EXTENSIONS = {".mov", ".mp4", ".avi", ".mkv", ".MOV", ".MP4", ".AVI", ".MKV"}

# Para testar primeiro, deixe MAX_VIDEOS = 5.
# Para extrair tudo, use MAX_VIDEOS = None.
MAX_VIDEOS = None

# Se True, não reprocessa vídeo cujo shard já existe.
RESUME = True

# Se include50_labels.txt não existir, cria uma seleção provisória de 50 classes.
AUTO_CREATE_LABELS_IF_MISSING = True

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
SHARDS_DIR.mkdir(parents=True, exist_ok=True)

print("RAW_ROOT:", RAW_ROOT)
print("OUTPUT_DIR:", OUTPUT_DIR)
print("LABELS_PATH:", LABELS_PATH)

RAW_ROOT: /Users/dani/Projects/islr-subset/data/raw/include50
OUTPUT_DIR: /Users/dani/Projects/islr-subset/data/interim/include50
LABELS_PATH: /Users/dani/Projects/islr-subset/data/raw/include50/include50_labels.txt

In [11]:
def norm_text(value) -> str:
    value = str(value).strip().lower()
    value = re.sub(r"\s+", " ", value)
    return value

def norm_key(value) -> str:
    parts = [norm_text(p) for p in str(value).split("::")]
    return "::".join(parts)

def slugify(value: str) -> str:
    value = str(value)
    value = value.replace("/", "__").replace("\\", "__")
    value = re.sub(r"[^A-Za-z0-9_\-.]+", "_", value)
    value = re.sub(r"_+", "_", value).strip("_")
    return value

def parse_class_folder(folder_name: str):
    # Exemplo: "1. loud" -> (1, "loud")
    m = re.match(r"^\s*(\d+(?:\.\d+)?)\.\s*(.+?)\s*$", folder_name)
    if not m:
        return np.nan, folder_name.strip()
    raw_id = m.group(1)
    sign = m.group(2).strip()
    try:
        original_class_id = int(float(raw_id))
    except Exception:
        original_class_id = np.nan
    return original_class_id, sign

def format_original_key(original_class_id, category, sign):
    if pd.isna(original_class_id):
        return f"{category}::{sign}"
    return f"{int(original_class_id):02d}::{category}::{sign}"

In [12]:
# Descobrir vídeos e montar metadata por vídeo

if not RAW_ROOT.exists():
    raise FileNotFoundError(f"Pasta não encontrada: {RAW_ROOT}")

video_paths = sorted([p for p in RAW_ROOT.rglob("*") if p.is_file() and p.suffix in VIDEO_EXTENSIONS])

print("Vídeos encontrados:", len(video_paths))

rows = []
bad_paths = []

for video_path in video_paths:
    rel = video_path.relative_to(RAW_ROOT)
    parts = rel.parts

    # Estrutura esperada:
    # pacote/categoria/classe/video
    # pacote/categoria/classe/Extra/video
    if len(parts) < 4:
        bad_paths.append(str(rel))
        continue

    package = parts[0]
    category = parts[1]
    class_folder = parts[2]

    original_class_id, sign = parse_class_folder(class_folder)

    class_key = f"{category}::{sign}"
    original_key = format_original_key(original_class_id, category, sign)

    # sequence_id precisa ser único mesmo se o mesmo MVI aparecer em outra categoria.
    sequence_base = str(rel.with_suffix(""))
    sequence_id = slugify(sequence_base)

    rows.append({
        "video_path": str(video_path),
        "video_relpath": str(rel),
        "package": package,
        "category": category,
        "class_folder": class_folder,
        "original_class_id": original_class_id,
        "sign": sign,
        "class_key": class_key,
        "original_key": original_key,
        "video_name": video_path.name,
        "sequence_id": sequence_id,
        "is_extra": any(norm_text(p) == "extra" for p in parts),
    })

metadata_all = pd.DataFrame(rows)

if bad_paths:
    print("Caminhos ignorados por estrutura inesperada:", len(bad_paths))
    print(bad_paths[:10])

print("Vídeos válidos no metadata:", len(metadata_all))
display(metadata_all.head())

Vídeos encontrados: 4284
Vídeos válidos no metadata: 4284

,video_path,video_relpath,package,category,class_folder,original_class_id,sign,class_key,original_key,video_name,sequence_id,is_extra
0,/Users/dani/Projects/islr-subset/data/raw/incl...,Adjectives_1of8/Adjectives/1. loud/MVI_5177.MOV,Adjectives_1of8,Adjectives,1. loud,1.0,loud,Adjectives::loud,01::Adjectives::loud,MVI_5177.MOV,Adjectives_1of8_Adjectives_1._loud_MVI_5177,False
1,/Users/dani/Projects/islr-subset/data/raw/incl...,Adjectives_1of8/Adjectives/1. loud/MVI_5178.MOV,Adjectives_1of8,Adjectives,1. loud,1.0,loud,Adjectives::loud,01::Adjectives::loud,MVI_5178.MOV,Adjectives_1of8_Adjectives_1._loud_MVI_5178,False
2,/Users/dani/Projects/islr-subset/data/raw/incl...,Adjectives_1of8/Adjectives/1. loud/MVI_5179.MOV,Adjectives_1of8,Adjectives,1. loud,1.0,loud,Adjectives::loud,01::Adjectives::loud,MVI_5179.MOV,Adjectives_1of8_Adjectives_1._loud_MVI_5179,False
3,/Users/dani/Projects/islr-subset/data/raw/incl...,Adjectives_1of8/Adjectives/1. loud/MVI_5257.MOV,Adjectives_1of8,Adjectives,1. loud,1.0,loud,Adjectives::loud,01::Adjectives::loud,MVI_5257.MOV,Adjectives_1of8_Adjectives_1._loud_MVI_5257,False
4,/Users/dani/Projects/islr-subset/data/raw/incl...,Adjectives_1of8/Adjectives/1. loud/MVI_5258.MOV,Adjectives_1of8,Adjectives,1. loud,1.0,loud,Adjectives::loud,01::Adjectives::loud,MVI_5258.MOV,Adjectives_1of8_Adjectives_1._loud_MVI_5258,False

In [13]:
# Inventário de classes disponíveis

classes_df = (
    metadata_all
    .groupby(["class_key", "original_key", "category", "sign", "original_class_id"], dropna=False)
    .agg(
        n_videos=("sequence_id", "nunique"),
        first_video=("video_relpath", "first"),
    )
    .reset_index()
    .sort_values(["category", "original_class_id", "sign"])
    .reset_index(drop=True)
)

classes_df.to_csv(INVENTORY_PATH, index=False)

print("Inventário salvo em:", INVENTORY_PATH)
print("Total de classes encontradas:", len(classes_df))
display(classes_df.head(30))

Inventário salvo em: /Users/dani/Projects/islr-subset/data/interim/include50/include50_discovered_classes.csv
Total de classes encontradas: 262

,class_key,original_key,category,sign,original_class_id,n_videos,first_video
0,Adjectives::loud,01::Adjectives::loud,Adjectives,loud,1.0,21,Adjectives_1of8/Adjectives/1. loud/MVI_5177.MOV
1,Adjectives::quiet,02::Adjectives::quiet,Adjectives,quiet,2.0,21,Adjectives_1of8/Adjectives/2. quiet/MVI_5180.MOV
2,Adjectives::happy,03::Adjectives::happy,Adjectives,happy,3.0,21,Adjectives_1of8/Adjectives/3. happy/MVI_5183.MOV
3,Adjectives::sad,04::Adjectives::sad,Adjectives,sad,4.0,8,Adjectives_1of8/Adjectives/4. sad/MVI_9565.MOV
4,Adjectives::Beautiful,05::Adjectives::Beautiful,Adjectives,Beautiful,5.0,9,Adjectives_1of8/Adjectives/5. Beautiful/Extra/...
5,Adjectives::Ugly,06::Adjectives::Ugly,Adjectives,Ugly,6.0,8,Adjectives_1of8/Adjectives/6. Ugly/MVI_9576.MOV
6,Adjectives::Deaf,07::Adjectives::Deaf,Adjectives,Deaf,7.0,8,Adjectives_1of8/Adjectives/7. Deaf/MVI_9580.MOV
7,Adjectives::Blind,08::Adjectives::Blind,Adjectives,Blind,8.0,8,Adjectives_1of8/Adjectives/8. Blind/MVI_9584.MOV
8,Adjectives::Nice,09::Adjectives::Nice,Adjectives,Nice,9.0,4,Adjectives_2of8/Adjectives/9. Nice/MVI_9588.MOV
9,Adjectives::Mean,10::Adjectives::Mean,Adjectives,Mean,10.0,8,Adjectives_2of8/Adjectives/10. Mean/MVI_9592.MOV
10,Adjectives::rich,11::Adjectives::rich,Adjectives,rich,11.0,8,Adjectives_2of8/Adjectives/11. rich/MVI_9596.MOV
11,Adjectives::poor,12::Adjectives::poor,Adjectives,poor,12.0,8,Adjectives_2of8/Adjectives/12. poor/MVI_9600.MOV
12,Adjectives::thick,13::Adjectives::thick,Adjectives,thick,13.0,8,Adjectives_2of8/Adjectives/13. thick/MVI_9605.MOV
13,Adjectives::thin,14::Adjectives::thin,Adjectives,thin,14.0,4,Adjectives_2of8/Adjectives/14. thin/MVI_9609.MOV
14,Adjectives::expensive,15::Adjectives::expensive,Adjectives,expensive,15.0,8,Adjectives_2of8/Adjectives/15. expensive/MVI_9...
15,Adjectives::cheap,16::Adjectives::cheap,Adjectives,cheap,16.0,8,Adjectives_2of8/Adjectives/16. cheap/MVI_9617.MOV
16,Adjectives::flat,17::Adjectives::flat,Adjectives,flat,17.0,8,Adjectives_2of8/Adjectives/17. flat/MVI_9621.MOV
17,Adjectives::curved,18::Adjectives::curved,Adjectives,curved,18.0,8,Adjectives_2of8/Adjectives/18. curved/MVI_9633...
18,Adjectives::male,19::Adjectives::male,Adjectives,male,19.0,8,Adjectives_2of8/Adjectives/19. male/MVI_9637.MOV
19,Adjectives::female,20::Adjectives::female,Adjectives,female,20.0,8,Adjectives_2of8/Adjectives/20. female/MVI_9642...
20,Adjectives::tight,21::Adjectives::tight,Adjectives,tight,21.0,8,Adjectives_2of8/Adjectives/21. tight/MVI_9646.MOV
21,Adjectives::loose,22::Adjectives::loose,Adjectives,loose,22.0,8,Adjectives_2of8/Adjectives/22. loose/MVI_9650.MOV
22,Adjectives::high,23::Adjectives::high,Adjectives,high,23.0,8,Adjectives_3of8/Adjectives/23. high/MVI_9654.MOV
23,Adjectives::low,24::Adjectives::low,Adjectives,low,24.0,8,Adjectives_3of8/Adjectives/24. low/MVI_9658.MOV
24,Adjectives::soft,25::Adjectives::soft,Adjectives,soft,25.0,8,Adjectives_3of8/Adjectives/25. soft/MVI_9662.MOV
25,Adjectives::hard,26::Adjectives::hard,Adjectives,hard,26.0,8,Adjectives_3of8/Adjectives/26. hard/MVI_9666.MOV
26,Adjectives::deep,27::Adjectives::deep,Adjectives,deep,27.0,8,Adjectives_3of8/Adjectives/27. deep/MVI_9670.MOV
27,Adjectives::shallow,28::Adjectives::shallow,Adjectives,shallow,28.0,8,Adjectives_3of8/Adjectives/28. shallow/MVI_967...
28,Adjectives::clean,29::Adjectives::clean,Adjectives,clean,29.0,8,Adjectives_3of8/Adjectives/29. clean/MVI_9679.MOV
29,Adjectives::dirty,30::Adjectives::dirty,Adjectives,dirty,30.0,8,Adjectives_3of8/Adjectives/30. dirty/MVI_9684.MOV

In [14]:
def load_labels(path: Path) -> List[str]:
    labels = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        labels.append(line)
    return labels

def resolve_labels_to_class_keys(labels: List[str], classes_df: pd.DataFrame) -> List[str]:
    classes_df = classes_df.copy()

    required_cols = ["class_key", "original_key", "sign"]
    missing = [c for c in required_cols if c not in classes_df.columns]
    if missing:
        raise ValueError(
            f"Inventário sem colunas esperadas: {missing}. "
            f"Colunas disponíveis: {classes_df.columns.tolist()}"
        )

    classes_df["norm_class_key"] = classes_df["class_key"].map(norm_key)
    classes_df["norm_original_key"] = classes_df["original_key"].map(norm_key)
    classes_df["norm_sign"] = classes_df["sign"].map(norm_text)

    resolved = []
    errors = []

    for label in labels:
        label_norm_key = norm_key(label)
        label_norm_text = norm_text(label)

        by_class_key = classes_df[classes_df["norm_class_key"] == label_norm_key]
        by_original_key = classes_df[classes_df["norm_original_key"] == label_norm_key]
        by_sign = classes_df[classes_df["norm_sign"] == label_norm_text]

        if len(by_class_key) == 1:
            resolved.append(by_class_key.iloc[0]["class_key"])
        elif len(by_original_key) == 1:
            resolved.append(by_original_key.iloc[0]["class_key"])
        elif len(by_sign) == 1:
            resolved.append(by_sign.iloc[0]["class_key"])
        elif len(by_sign) > 1:
            errors.append(
                f"Label ambíguo '{label}'. Use category::sign. Opções: "
                + ", ".join(by_sign["class_key"].tolist())
            )
        else:
            errors.append(f"Label não encontrado: {label}")

    if errors:
        raise ValueError("\n".join(errors))

    # remove duplicados mantendo ordem
    unique = []
    seen = set()
    for key in resolved:
        if key not in seen:
            unique.append(key)
            seen.add(key)

    return unique

def auto_select_50_classes(classes_df: pd.DataFrame) -> List[str]:
    # Seleção automática provisória:
    # 1) prioriza classes com mais vídeos
    # 2) faz round-robin por categoria para não pegar tudo de uma categoria só
    df = classes_df.copy()
    df = df.sort_values(["category", "n_videos", "original_class_id", "sign"], ascending=[True, False, True, True])

    selected = []
    selected_set = set()

    categories = sorted(df["category"].dropna().unique().tolist())

    while len(selected) < 50:
        added = False
        for category in categories:
            cand = df[(df["category"] == category) & (~df["class_key"].isin(selected_set))]
            if cand.empty:
                continue
            row = cand.iloc[0]
            selected.append(row["class_key"])
            selected_set.add(row["class_key"])
            added = True
            if len(selected) == 50:
                break
        if not added:
            break

    if len(selected) < 50:
        raise ValueError(f"Não foi possível selecionar 50 classes. Selecionadas: {len(selected)}")

    return selected

if not LABELS_PATH.exists():
    if not AUTO_CREATE_LABELS_IF_MISSING:
        raise FileNotFoundError(
            f"Arquivo de labels não encontrado: {LABELS_PATH}\n"
            f"Inventário salvo em: {INVENTORY_PATH}\n"
            "Crie include50_labels.txt com 50 linhas no formato Categoria::Sinal."
        )

    selected_class_keys = auto_select_50_classes(classes_df)
    LABELS_PATH.write_text("\n".join(selected_class_keys) + "\n", encoding="utf-8")
    print("ATENÇÃO: include50_labels.txt não existia.")
    print("Foi criada uma seleção PROVISÓRIA automática de 50 classes.")
    print("Arquivo criado em:", LABELS_PATH)
else:
    raw_labels = load_labels(LABELS_PATH)
    selected_class_keys = resolve_labels_to_class_keys(raw_labels, classes_df)
    print("Labels carregados:", len(raw_labels))
    print("Classes resolvidas:", len(selected_class_keys))

if len(selected_class_keys) != 50:
    raise ValueError(f"Esperava 50 classes, mas foram resolvidas {len(selected_class_keys)}.")

selected_classes = classes_df[classes_df["class_key"].isin(selected_class_keys)].copy()
selected_classes = selected_classes.set_index("class_key").loc[selected_class_keys].reset_index()
selected_classes["new_sign_id"] = range(len(selected_classes))

selected_classes.to_csv(SELECTED_CLASSES_PATH, index=False)

print("Classes selecionadas:", len(selected_classes))
print("Classes salvas em:", SELECTED_CLASSES_PATH)
display(selected_classes[["new_sign_id", "class_key", "original_key", "n_videos"]])

Labels carregados: 50
Classes resolvidas: 50
Classes selecionadas: 50
Classes salvas em: /Users/dani/Projects/islr-subset/data/interim/include50/include50_selected_classes.csv

,new_sign_id,class_key,original_key,n_videos
0,0,Adjectives::short,79::Adjectives::short,22
1,1,Animals::Bird,04::Animals::Bird,25
2,2,Clothes::Hat,37::Clothes::Hat,20
3,3,Colours::Brown,51::Colours::Brown,21
4,4,Days_and_Time::Year,78::Days_and_Time::Year,15
5,5,Electronics::Fan,53::Electronics::Fan,15
6,6,Greetings::Good afternoon,52::Greetings::Good afternoon,22
7,7,Home::Paint,40::Home::Paint,15
8,8,Jobs::Priest,91::Jobs::Priest,15
9,9,Means_of_Transportation::Train,09::Means_of_Transportation::Train,21
10,10,People::Brother,66::People::Brother,21
11,11,Places::Court,23::Places::Court,23
12,12,Pronouns::I,40::Pronouns::I,21
13,13,Seasons::Fall,64::Seasons::Fall,15
14,14,Society::Attack,13::Society::Attack,15
15,15,Adjectives::small little,84::Adjectives::small little,22
16,16,Animals::Cow,05::Animals::Cow,21
17,17,Clothes::Dress,38::Clothes::Dress,20
18,18,Colours::Grey,56::Colours::Grey,21
19,19,Days_and_Time::Second,81::Days_and_Time::Second,15
20,20,Electronics::Lamp,52::Electronics::Lamp,14
21,21,Greetings::Hello,48::Greetings::Hello,21
22,22,Home::Table,24::Home::Table,14
23,23,Jobs::Teacher,84::Jobs::Teacher,14
24,24,Means_of_Transportation::Plane,10::Means_of_Transportation::Plane,21
25,25,People::Boy,77::People::Boy,21
26,26,Places::Train Station,21::Places::Train Station,22
27,27,Pronouns::you,41::Pronouns::you,21
28,28,Seasons::Summer,61::Seasons::Summer,14
29,29,Society::Ball,19::Society::Ball,15
30,30,Adjectives::loud,01::Adjectives::loud,21
31,31,Animals::Dog,01::Animals::Dog,20
32,32,Clothes::Shirt,41::Clothes::Shirt,20
33,33,Colours::Red,47::Colours::Red,20
34,34,Days_and_Time::Night,85::Days_and_Time::Night,15
35,35,Electronics::Cell phone,54::Electronics::Cell phone,14
36,36,Greetings::How are you,49::Greetings::How are you,21
37,37,Home::Chair,25::Home::Chair,14
38,38,Jobs::Student,85::Jobs::Student,14
39,39,Means_of_Transportation::Truck,12::Means_of_Transportation::Truck,21
40,40,People::Son,58::People::Son,20
41,41,Places::Park,27::Places::Park,22
42,42,Pronouns::he,42::Pronouns::he,21
43,43,Seasons::Spring,62::Seasons::Spring,14
44,44,Society::Religion,01::Society::Religion,14
45,45,Adjectives::quiet,02::Adjectives::quiet,21
46,46,Animals::Cat,02::Animals::Cat,20
47,47,Clothes::T-Shirt,42::Clothes::T-Shirt,20
48,48,Colours::Green,48::Colours::Green,20
49,49,Days_and_Time::Time,86::Days_and_Time::Time,15

In [15]:
# Filtrar metadata para as 50 classes e recriar sign_id global 0..49

class_to_new_id = dict(zip(selected_classes["class_key"], selected_classes["new_sign_id"]))

metadata = metadata_all[metadata_all["class_key"].isin(selected_class_keys)].copy()
metadata["sign_id"] = metadata["class_key"].map(class_to_new_id).astype(int)
metadata["sign_key"] = metadata["sign_id"].astype(str).str.zfill(2) + "::" + metadata["category"] + "::" + metadata["sign"]

# sample_id dentro de cada classe, só para referência
metadata = metadata.sort_values(["sign_id", "video_relpath"]).reset_index(drop=True)
metadata["sample_id"] = metadata.groupby("sign_id").cumcount()

print("Vídeos selecionados:", metadata["sequence_id"].nunique())
print("Classes:", metadata["sign_id"].nunique())
print()
print(metadata.groupby(["sign_id", "class_key"])["sequence_id"].nunique().head(60).to_string())

display(metadata.head())

Vídeos selecionados: 929
Classes: 50

sign_id  class_key
0        Adjectives::short                 22
1        Animals::Bird                     25
2        Clothes::Hat                      20
3        Colours::Brown                    21
4        Days_and_Time::Year               15
5        Electronics::Fan                  15
6        Greetings::Good afternoon         22
7        Home::Paint                       15
8        Jobs::Priest                      15
9        Means_of_Transportation::Train    21
10       People::Brother                   21
11       Places::Court                     23
12       Pronouns::I                       21
13       Seasons::Fall                     15
14       Society::Attack                   15
15       Adjectives::small little          22
16       Animals::Cow                      21
17       Clothes::Dress                    20
18       Colours::Grey                     21
19       Days_and_Time::Second             15
20       Electronics::Lamp                 14
21       Greetings::Hello                  21
22       Home::Table                       14
23       Jobs::Teacher                     14
24       Means_of_Transportation::Plane    21
25       People::Boy                       21
26       Places::Train Station             22
27       Pronouns::you                     21
28       Seasons::Summer                   14
29       Society::Ball                     15
30       Adjectives::loud                  21
31       Animals::Dog                      20
32       Clothes::Shirt                    20
33       Colours::Red                      20
34       Days_and_Time::Night              15
35       Electronics::Cell phone           14
36       Greetings::How are you            21
37       Home::Chair                       14
38       Jobs::Student                     14
39       Means_of_Transportation::Truck    21
40       People::Son                       20
41       Places::Park                      22
42       Pronouns::he                      21
43       Seasons::Spring                   14
44       Society::Religion                 14
45       Adjectives::quiet                 21
46       Animals::Cat                      20
47       Clothes::T-Shirt                  20
48       Colours::Green                    20
49       Days_and_Time::Time               15

,video_path,video_relpath,package,category,class_folder,original_class_id,sign,class_key,original_key,video_name,sequence_id,is_extra,sign_id,sign_key,sample_id
0,/Users/dani/Projects/islr-subset/data/raw/incl...,Adjectives_4of8/Adjectives/79. short/MVI_5110.MOV,Adjectives_4of8,Adjectives,79. short,79.0,short,Adjectives::short,79::Adjectives::short,MVI_5110.MOV,Adjectives_4of8_Adjectives_79._short_MVI_5110,False,0,00::Adjectives::short,0
1,/Users/dani/Projects/islr-subset/data/raw/incl...,Adjectives_4of8/Adjectives/79. short/MVI_5111.MOV,Adjectives_4of8,Adjectives,79. short,79.0,short,Adjectives::short,79::Adjectives::short,MVI_5111.MOV,Adjectives_4of8_Adjectives_79._short_MVI_5111,False,0,00::Adjectives::short,1
2,/Users/dani/Projects/islr-subset/data/raw/incl...,Adjectives_4of8/Adjectives/79. short/MVI_5112.MOV,Adjectives_4of8,Adjectives,79. short,79.0,short,Adjectives::short,79::Adjectives::short,MVI_5112.MOV,Adjectives_4of8_Adjectives_79._short_MVI_5112,False,0,00::Adjectives::short,2
3,/Users/dani/Projects/islr-subset/data/raw/incl...,Adjectives_4of8/Adjectives/79. short/MVI_5189.MOV,Adjectives_4of8,Adjectives,79. short,79.0,short,Adjectives::short,79::Adjectives::short,MVI_5189.MOV,Adjectives_4of8_Adjectives_79._short_MVI_5189,False,0,00::Adjectives::short,3
4,/Users/dani/Projects/islr-subset/data/raw/incl...,Adjectives_4of8/Adjectives/79. short/MVI_5190.MOV,Adjectives_4of8,Adjectives,79. short,79.0,short,Adjectives::short,79::Adjectives::short,MVI_5190.MOV,Adjectives_4of8_Adjectives_79._short_MVI_5190,False,0,00::Adjectives::short,4

In [16]:
# Instalação/imports da extração
# Se der erro de import mediapipe, instale no terminal:
# python -m pip install mediapipe==0.10.5 opencv-python-headless tqdm

import cv2
from tqdm.auto import tqdm
import mediapipe as mp

mp_holistic = mp.solutions.holistic

In [17]:
# Funções para extrair landmarks em formato wide

def empty_landmarks(prefix: str, n_points: int) -> Dict[str, float]:
    row = {}
    for i in range(n_points):
        row[f"{prefix}_{i}_x"] = np.nan
        row[f"{prefix}_{i}_y"] = np.nan
        row[f"{prefix}_{i}_z"] = np.nan
    return row

def add_landmarks(row: Dict[str, float], prefix: str, landmarks, n_points: int):
    if landmarks is None:
        row.update(empty_landmarks(prefix, n_points))
        return True

    pts = landmarks.landmark
    for i in range(n_points):
        if i < len(pts):
            row[f"{prefix}_{i}_x"] = pts[i].x
            row[f"{prefix}_{i}_y"] = pts[i].y
            row[f"{prefix}_{i}_z"] = pts[i].z
        else:
            row[f"{prefix}_{i}_x"] = np.nan
            row[f"{prefix}_{i}_y"] = np.nan
            row[f"{prefix}_{i}_z"] = np.nan
    return False

def shard_path_for_sequence(sequence_id: str) -> Path:
    return SHARDS_DIR / f"{sequence_id}.csv"

def extract_video_to_rows(video_meta: pd.Series, holistic) -> pd.DataFrame:
    video_path = video_meta["video_path"]
    cap = cv2.VideoCapture(str(video_path))

    if not cap.isOpened():
        raise RuntimeError(f"Não foi possível abrir vídeo: {video_path}")

    rows = []
    frame_id = 0

    while True:
        ok, frame = cap.read()
        if not ok:
            break

        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        result = holistic.process(rgb)

        row = {
            "sign_id": int(video_meta["sign_id"]),
            "category": video_meta["category"],
            "sign": video_meta["sign"],
            "sign_key": video_meta["sign_key"],
            "sample_id": int(video_meta["sample_id"]),
            "video_name": video_meta["video_name"],
            "video_relpath": video_meta["video_relpath"],
            "sequence_id": video_meta["sequence_id"],
            "frame_id": frame_id,
        }

        missing_hand_0 = add_landmarks(row, "hand_0", result.left_hand_landmarks, 21)
        missing_hand_1 = add_landmarks(row, "hand_1", result.right_hand_landmarks, 21)
        missing_pose = add_landmarks(row, "pose", result.pose_landmarks, 33)
        missing_face = add_landmarks(row, "face", result.face_landmarks, 468)

        row["missing_hand_0"] = bool(missing_hand_0)
        row["missing_hand_1"] = bool(missing_hand_1)
        row["missing_hand"] = bool(missing_hand_0 and missing_hand_1)
        row["missing_pose"] = bool(missing_pose)
        row["missing_face"] = bool(missing_face)

        rows.append(row)
        frame_id += 1

    cap.release()

    if not rows:
        raise RuntimeError(f"Vídeo sem frames lidos: {video_path}")

    return pd.DataFrame(rows)

In [18]:
# Teste/extração
# Com MAX_VIDEOS = 5, processa só 5 vídeos para validar.
# Depois mude MAX_VIDEOS = None na primeira célula para extrair tudo.

to_process = metadata.copy()

if MAX_VIDEOS is not None:
    to_process = to_process.head(MAX_VIDEOS).copy()

print("Vídeos nesta execução:", len(to_process))
print("RESUME:", RESUME)

with mp_holistic.Holistic(
    static_image_mode=False,
    model_complexity=1,
    smooth_landmarks=True,
    enable_segmentation=False,
    smooth_segmentation=False,
    refine_face_landmarks=False,
    min_detection_confidence=0.4,
    min_tracking_confidence=0.4,
) as holistic:
    for _, video_meta in tqdm(to_process.iterrows(), total=len(to_process)):
        out_path = shard_path_for_sequence(video_meta["sequence_id"])

        if RESUME and out_path.exists():
            continue

        try:
            shard_df = extract_video_to_rows(video_meta, holistic)
            shard_df.to_csv(out_path, index=False)
        except Exception as exc:
            error_path = out_path.with_suffix(".error.txt")
            error_path.write_text(str(exc), encoding="utf-8")
            print("Erro em:", video_meta["video_relpath"])
            print(exc)

print("Shards existentes:", len(list(SHARDS_DIR.glob('*.csv'))))

I0000 00:00:1782443915.604682 3485154 gl_context.cc:357] GL version: 2.1 (2.1 Metal - 90.5), renderer: Apple M1 Pro

Vídeos nesta execução: 929
RESUME: True

  0%|          | 0/929 [00:00<?, ?it/s]W0000 00:00:1782443915.677214 3488276 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1782443915.687258 3488279 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1782443915.689870 3488283 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1782443915.689926 3488274 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1782443915.689995 3488280 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1782443915.692729 3488280 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1782443915.693230 3488283 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1782443915.694417 3488275 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
/opt/homebrew/lib/python3.10/site-packages/google/protobuf/symbol_database.py:55: UserWarning: SymbolDatabase.GetPrototype() is deprecated. Please use message_factory.GetMessageClass() instead. SymbolDatabase.GetPrototype() will be removed soon.
  warnings.warn('SymbolDatabase.GetPrototype() is deprecated. Please '
100%|██████████| 929/929 [40:53<00:00,  2.64s/it]

Shards existentes: 929

In [19]:
# Juntar shards em um CSV final

shard_files = sorted(SHARDS_DIR.glob("*.csv"))

if not shard_files:
    raise RuntimeError("Nenhum shard CSV encontrado.")

dfs = []
for path in tqdm(shard_files):
    dfs.append(pd.read_csv(path))

final_df = pd.concat(dfs, ignore_index=True)

# Ordenação organizada
final_df = final_df.sort_values(["sign_id", "sequence_id", "frame_id"]).reset_index(drop=True)

final_df.to_csv(FINAL_CSV_PATH, index=False)

print("CSV final salvo em:", FINAL_CSV_PATH)
print("Linhas:", len(final_df))
print("Vídeos:", final_df["sequence_id"].nunique())
print("Classes:", final_df["sign_id"].nunique())

display(final_df.head())

100%|██████████| 929/929 [00:24<00:00, 38.56it/s]

CSV final salvo em: /Users/dani/Projects/islr-subset/data/interim/include50/include50_mediapipe.csv
Linhas: 61613
Vídeos: 929
Classes: 50

,sign_id,category,sign,sign_key,sample_id,video_name,video_relpath,sequence_id,frame_id,hand_0_0_x,...,face_466_y,face_466_z,face_467_x,face_467_y,face_467_z,missing_hand_0,missing_hand_1,missing_hand,missing_pose,missing_face
0,0,Adjectives,short,00::Adjectives::short,0,MVI_5110.MOV,Adjectives_4of8/Adjectives/79. short/MVI_5110.MOV,Adjectives_4of8_Adjectives_79._short_MVI_5110,0,0.567757,...,0.236819,0.004603,0.510011,0.235687,0.004731,False,False,False,False,False
1,0,Adjectives,short,00::Adjectives::short,0,MVI_5110.MOV,Adjectives_4of8/Adjectives/79. short/MVI_5110.MOV,Adjectives_4of8_Adjectives_79._short_MVI_5110,1,0.566954,...,0.236412,0.004434,0.510173,0.235442,0.004542,False,False,False,False,False
2,0,Adjectives,short,00::Adjectives::short,0,MVI_5110.MOV,Adjectives_4of8/Adjectives/79. short/MVI_5110.MOV,Adjectives_4of8_Adjectives_79._short_MVI_5110,2,0.566794,...,0.236553,0.004450,0.510262,0.235473,0.004558,False,False,False,False,False
3,0,Adjectives,short,00::Adjectives::short,0,MVI_5110.MOV,Adjectives_4of8/Adjectives/79. short/MVI_5110.MOV,Adjectives_4of8_Adjectives_79._short_MVI_5110,3,0.566527,...,0.236887,0.004306,0.510315,0.235753,0.004415,False,False,False,False,False
4,0,Adjectives,short,00::Adjectives::short,0,MVI_5110.MOV,Adjectives_4of8/Adjectives/79. short/MVI_5110.MOV,Adjectives_4of8_Adjectives_79._short_MVI_5110,4,0.565466,...,0.236952,0.004398,0.510433,0.235741,0.004511,False,False,False,False,False

In [20]:
# Validação final

df = pd.read_csv(FINAL_CSV_PATH, usecols=[
    "sign_id", "category", "sign", "sign_key", "sample_id",
    "video_name", "video_relpath", "sequence_id", "frame_id",
    "missing_hand", "missing_hand_0", "missing_hand_1", "missing_face", "missing_pose"
])

videos = df.drop_duplicates("sequence_id")

print("Classes:", videos["sign_id"].nunique())
print("Sinais:", videos["sign_key"].nunique())
print("Vídeos:", videos["sequence_id"].nunique())
print("Frames:", len(df))

print("\nVídeos por classe:")
print(videos.groupby(["sign_id", "sign_key"])["sequence_id"].nunique().to_string())

print("\nMissing médio por frame:")
print(df[["missing_hand", "missing_hand_0", "missing_hand_1", "missing_face", "missing_pose"]].mean())

Classes: 50
Sinais: 50
Vídeos: 929
Frames: 61613

Vídeos por classe:
sign_id  sign_key
0        00::Adjectives::short                 22
1        01::Animals::Bird                     25
2        02::Clothes::Hat                      20
3        03::Colours::Brown                    21
4        04::Days_and_Time::Year               15
5        05::Electronics::Fan                  15
6        06::Greetings::Good afternoon         22
7        07::Home::Paint                       15
8        08::Jobs::Priest                      15
9        09::Means_of_Transportation::Train    21
10       10::People::Brother                   21
11       11::Places::Court                     23
12       12::Pronouns::I                       21
13       13::Seasons::Fall                     15
14       14::Society::Attack                   15
15       15::Adjectives::small little          22
16       16::Animals::Cow                      21
17       17::Clothes::Dress                    20
18       18::Colours::Grey                     21
19       19::Days_and_Time::Second             15
20       20::Electronics::Lamp                 14
21       21::Greetings::Hello                  21
22       22::Home::Table                       14
23       23::Jobs::Teacher                     14
24       24::Means_of_Transportation::Plane    21
25       25::People::Boy                       21
26       26::Places::Train Station             22
27       27::Pronouns::you                     21
28       28::Seasons::Summer                   14
29       29::Society::Ball                     15
30       30::Adjectives::loud                  21
31       31::Animals::Dog                      20
32       32::Clothes::Shirt                    20
33       33::Colours::Red                      20
34       34::Days_and_Time::Night              15
35       35::Electronics::Cell phone           14
36       36::Greetings::How are you            21
37       37::Home::Chair                       14
38       38::Jobs::Student                     14
39       39::Means_of_Transportation::Truck    21
40       40::People::Son                       20
41       41::Places::Park                      22
42       42::Pronouns::he                      21
43       43::Seasons::Spring                   14
44       44::Society::Religion                 14
45       45::Adjectives::quiet                 21
46       46::Animals::Cat                      20
47       47::Clothes::T-Shirt                  20
48       48::Colours::Green                    20
49       49::Days_and_Time::Time               15

Missing médio por frame:
missing_hand      0.098599
missing_hand_0    0.169282
missing_hand_1    0.266746
missing_face      0.000357
missing_pose      0.000000
dtype: float64

Para o INCLUDE-50, não foi aplicado o protocolo Leave-One-Person-Out, uma vez que a versão utilizada do dataset não disponibiliza identificadores dos sinalizadores. Seguindo a restrição metodológica observada em Alves, Boldt e Paixão, a avaliação foi conduzida por meio de uma divisão fixa em treino, validação e teste. Na ausência de um arquivo oficial de particionamento na versão obtida, os vídeos foram divididos de forma estratificada por classe, garantindo que todas as amostras de uma mesma sequência permanecessem em apenas um dos subconjuntos.

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

input_csv = PROJECT_ROOT / "data/interim/include50/include50_mediapipe.csv"
output_csv = PROJECT_ROOT / "data/interim/include50/include50_mediapipe_with_split.csv"

df = pd.read_csv(input_csv)

# Uma linha por vídeo
videos = (
    df[["sequence_id", "sign_id", "sign", "sign_key"]]
    .drop_duplicates("sequence_id")
    .copy()
)

print("Vídeos:", videos["sequence_id"].nunique())
print("Classes:", videos["sign_id"].nunique())

# 15% teste
trainval, test = train_test_split(
    videos,
    test_size=0.15,
    stratify=videos["sign_id"],
    random_state=42,
)

# Dos 85% restantes, separa validação para dar 15% do total
val_size_adjusted = 0.15 / 0.85

train, val = train_test_split(
    trainval,
    test_size=val_size_adjusted,
    stratify=trainval["sign_id"],
    random_state=42,
)

split_map = {}
split_map.update({sid: "train" for sid in train["sequence_id"]})
split_map.update({sid: "val" for sid in val["sequence_id"]})
split_map.update({sid: "test" for sid in test["sequence_id"]})

df["split"] = df["sequence_id"].map(split_map)

print("\nDistribuição geral:")
print(df.drop_duplicates("sequence_id")["split"].value_counts())

print("\nDistribuição por classe:")
print(
    df.drop_duplicates("sequence_id")
      .groupby(["split", "sign_id"])
      .size()
      .groupby("split")
      .describe()
)

df.to_csv(output_csv, index=False)

print("\nSalvo em:", output_csv)

Vídeos: 929
Classes: 50

Distribuição geral:
split
train    649
val      140
test     140
Name: count, dtype: int64

Distribuição por classe:
       count   mean       std   min   25%   50%   75%   max
split
test    50.0   2.80  0.670059   2.0   2.0   3.0   3.0   4.0
train   50.0  12.98  2.368932  10.0  10.0  14.0  15.0  17.0
val     50.0   2.80  0.494872   2.0   3.0   3.0   3.0   4.0

Salvo em: /Users/dani/Projetos/islr-subset/data/interim/include50/include50_mediapipe_with_split.csv

In [2]:
import pandas as pd

path = "../data/interim/include50/include50_mediapipe_with_split.csv"
df = pd.read_csv(path, nrows=5)

print(df.columns.tolist())
print(df[["sign_id", "category", "sign", "sequence_id", "video_name", "frame_id", "split"]].head())

['sign_id', 'category', 'sign', 'sign_key', 'sample_id', 'video_name', 'video_relpath', 'sequence_id', 'frame_id', 'hand_0_0_x', 'hand_0_0_y', 'hand_0_0_z', 'hand_0_1_x', 'hand_0_1_y', 'hand_0_1_z', 'hand_0_2_x', 'hand_0_2_y', 'hand_0_2_z', 'hand_0_3_x', 'hand_0_3_y', 'hand_0_3_z', 'hand_0_4_x', 'hand_0_4_y', 'hand_0_4_z', 'hand_0_5_x', 'hand_0_5_y', 'hand_0_5_z', 'hand_0_6_x', 'hand_0_6_y', 'hand_0_6_z', 'hand_0_7_x', 'hand_0_7_y', 'hand_0_7_z', 'hand_0_8_x', 'hand_0_8_y', 'hand_0_8_z', 'hand_0_9_x', 'hand_0_9_y', 'hand_0_9_z', 'hand_0_10_x', 'hand_0_10_y', 'hand_0_10_z', 'hand_0_11_x', 'hand_0_11_y', 'hand_0_11_z', 'hand_0_12_x', 'hand_0_12_y', 'hand_0_12_z', 'hand_0_13_x', 'hand_0_13_y', 'hand_0_13_z', 'hand_0_14_x', 'hand_0_14_y', 'hand_0_14_z', 'hand_0_15_x', 'hand_0_15_y', 'hand_0_15_z', 'hand_0_16_x', 'hand_0_16_y', 'hand_0_16_z', 'hand_0_17_x', 'hand_0_17_y', 'hand_0_17_z', 'hand_0_18_x', 'hand_0_18_y', 'hand_0_18_z', 'hand_0_19_x', 'hand_0_19_y', 'hand_0_19_z', 'hand_0_20_x', 'hand_0_20_y', 'hand_0_20_z', 'hand_1_0_x', 'hand_1_0_y', 'hand_1_0_z', 'hand_1_1_x', 'hand_1_1_y', 'hand_1_1_z', 'hand_1_2_x', 'hand_1_2_y', 'hand_1_2_z', 'hand_1_3_x', 'hand_1_3_y', 'hand_1_3_z', 'hand_1_4_x', 'hand_1_4_y', 'hand_1_4_z', 'hand_1_5_x', 'hand_1_5_y', 'hand_1_5_z', 'hand_1_6_x', 'hand_1_6_y', 'hand_1_6_z', 'hand_1_7_x', 'hand_1_7_y', 'hand_1_7_z', 'hand_1_8_x', 'hand_1_8_y', 'hand_1_8_z', 'hand_1_9_x', 'hand_1_9_y', 'hand_1_9_z', 'hand_1_10_x', 'hand_1_10_y', 'hand_1_10_z', 'hand_1_11_x', 'hand_1_11_y', 'hand_1_11_z', 'hand_1_12_x', 'hand_1_12_y', 'hand_1_12_z', 'hand_1_13_x', 'hand_1_13_y', 'hand_1_13_z', 'hand_1_14_x', 'hand_1_14_y', 'hand_1_14_z', 'hand_1_15_x', 'hand_1_15_y', 'hand_1_15_z', 'hand_1_16_x', 'hand_1_16_y', 'hand_1_16_z', 'hand_1_17_x', 'hand_1_17_y', 'hand_1_17_z', 'hand_1_18_x', 'hand_1_18_y', 'hand_1_18_z', 'hand_1_19_x', 'hand_1_19_y', 'hand_1_19_z', 'hand_1_20_x', 'hand_1_20_y', 'hand_1_20_z', 'pose_0_x', 'pose_0_y', 'pose_0_z', 'pose_1_x', 'pose_1_y', 'pose_1_z', 'pose_2_x', 'pose_2_y', 'pose_2_z', 'pose_3_x', 'pose_3_y', 'pose_3_z', 'pose_4_x', 'pose_4_y', 'pose_4_z', 'pose_5_x', 'pose_5_y', 'pose_5_z', 'pose_6_x', 'pose_6_y', 'pose_6_z', 'pose_7_x', 'pose_7_y', 'pose_7_z', 'pose_8_x', 'pose_8_y', 'pose_8_z', 'pose_9_x', 'pose_9_y', 'pose_9_z', 'pose_10_x', 'pose_10_y', 'pose_10_z', 'pose_11_x', 'pose_11_y', 'pose_11_z', 'pose_12_x', 'pose_12_y', 'pose_12_z', 'pose_13_x', 'pose_13_y', 'pose_13_z', 'pose_14_x', 'pose_14_y', 'pose_14_z', 'pose_15_x', 'pose_15_y', 'pose_15_z', 'pose_16_x', 'pose_16_y', 'pose_16_z', 'pose_17_x', 'pose_17_y', 'pose_17_z', 'pose_18_x', 'pose_18_y', 'pose_18_z', 'pose_19_x', 'pose_19_y', 'pose_19_z', 'pose_20_x', 'pose_20_y', 'pose_20_z', 'pose_21_x', 'pose_21_y', 'pose_21_z', 'pose_22_x', 'pose_22_y', 'pose_22_z', 'pose_23_x', 'pose_23_y', 'pose_23_z', 'pose_24_x', 'pose_24_y', 'pose_24_z', 'pose_25_x', 'pose_25_y', 'pose_25_z', 'pose_26_x', 'pose_26_y', 'pose_26_z', 'pose_27_x', 'pose_27_y', 'pose_27_z', 'pose_28_x', 'pose_28_y', 'pose_28_z', 'pose_29_x', 'pose_29_y', 'pose_29_z', 'pose_30_x', 'pose_30_y', 'pose_30_z', 'pose_31_x', 'pose_31_y', 'pose_31_z', 'pose_32_x', 'pose_32_y', 'pose_32_z', 'face_0_x', 'face_0_y', 'face_0_z', 'face_1_x', 'face_1_y', 'face_1_z', 'face_2_x', 'face_2_y', 'face_2_z', 'face_3_x', 'face_3_y', 'face_3_z', 'face_4_x', 'face_4_y', 'face_4_z', 'face_5_x', 'face_5_y', 'face_5_z', 'face_6_x', 'face_6_y', 'face_6_z', 'face_7_x', 'face_7_y', 'face_7_z', 'face_8_x', 'face_8_y', 'face_8_z', 'face_9_x', 'face_9_y', 'face_9_z', 'face_10_x', 'face_10_y', 'face_10_z', 'face_11_x', 'face_11_y', 'face_11_z', 'face_12_x', 'face_12_y', 'face_12_z', 'face_13_x', 'face_13_y', 'face_13_z', 'face_14_x', 'face_14_y', 'face_14_z', 'face_15_x', 'face_15_y', 'face_15_z', 'face_16_x', 'face_16_y', 'face_16_z', 'face_17_x', 'face_17_y', 'face_17_z', 'face_18_x', 'face_18_y', 'face_18_z', 'face_19_x', 'face_19_y', 'face_19_z', 'face_20_x', 'face_20_y', 'face_20_z', 'face_21_x', 'face_21_y', 'face_21_z', 'face_22_x', 'face_22_y', 'face_22_z', 'face_23_x', 'face_23_y', 'face_23_z', 'face_24_x', 'face_24_y', 'face_24_z', 'face_25_x', 'face_25_y', 'face_25_z', 'face_26_x', 'face_26_y', 'face_26_z', 'face_27_x', 'face_27_y', 'face_27_z', 'face_28_x', 'face_28_y', 'face_28_z', 'face_29_x', 'face_29_y', 'face_29_z', 'face_30_x', 'face_30_y', 'face_30_z', 'face_31_x', 'face_31_y', 'face_31_z', 'face_32_x', 'face_32_y', 'face_32_z', 'face_33_x', 'face_33_y', 'face_33_z', 'face_34_x', 'face_34_y', 'face_34_z', 'face_35_x', 'face_35_y', 'face_35_z', 'face_36_x', 'face_36_y', 'face_36_z', 'face_37_x', 'face_37_y', 'face_37_z', 'face_38_x', 'face_38_y', 'face_38_z', 'face_39_x', 'face_39_y', 'face_39_z', 'face_40_x', 'face_40_y', 'face_40_z', 'face_41_x', 'face_41_y', 'face_41_z', 'face_42_x', 'face_42_y', 'face_42_z', 'face_43_x', 'face_43_y', 'face_43_z', 'face_44_x', 'face_44_y', 'face_44_z', 'face_45_x', 'face_45_y', 'face_45_z', 'face_46_x', 'face_46_y', 'face_46_z', 'face_47_x', 'face_47_y', 'face_47_z', 'face_48_x', 'face_48_y', 'face_48_z', 'face_49_x', 'face_49_y', 'face_49_z', 'face_50_x', 'face_50_y', 'face_50_z', 'face_51_x', 'face_51_y', 'face_51_z', 'face_52_x', 'face_52_y', 'face_52_z', 'face_53_x', 'face_53_y', 'face_53_z', 'face_54_x', 'face_54_y', 'face_54_z', 'face_55_x', 'face_55_y', 'face_55_z', 'face_56_x', 'face_56_y', 'face_56_z', 'face_57_x', 'face_57_y', 'face_57_z', 'face_58_x', 'face_58_y', 'face_58_z', 'face_59_x', 'face_59_y', 'face_59_z', 'face_60_x', 'face_60_y', 'face_60_z', 'face_61_x', 'face_61_y', 'face_61_z', 'face_62_x', 'face_62_y', 'face_62_z', 'face_63_x', 'face_63_y', 'face_63_z', 'face_64_x', 'face_64_y', 'face_64_z', 'face_65_x', 'face_65_y', 'face_65_z', 'face_66_x', 'face_66_y', 'face_66_z', 'face_67_x', 'face_67_y', 'face_67_z', 'face_68_x', 'face_68_y', 'face_68_z', 'face_69_x', 'face_69_y', 'face_69_z', 'face_70_x', 'face_70_y', 'face_70_z', 'face_71_x', 'face_71_y', 'face_71_z', 'face_72_x', 'face_72_y', 'face_72_z', 'face_73_x', 'face_73_y', 'face_73_z', 'face_74_x', 'face_74_y', 'face_74_z', 'face_75_x', 'face_75_y', 'face_75_z', 'face_76_x', 'face_76_y', 'face_76_z', 'face_77_x', 'face_77_y', 'face_77_z', 'face_78_x', 'face_78_y', 'face_78_z', 'face_79_x', 'face_79_y', 'face_79_z', 'face_80_x', 'face_80_y', 'face_80_z', 'face_81_x', 'face_81_y', 'face_81_z', 'face_82_x', 'face_82_y', 'face_82_z', 'face_83_x', 'face_83_y', 'face_83_z', 'face_84_x', 'face_84_y', 'face_84_z', 'face_85_x', 'face_85_y', 'face_85_z', 'face_86_x', 'face_86_y', 'face_86_z', 'face_87_x', 'face_87_y', 'face_87_z', 'face_88_x', 'face_88_y', 'face_88_z', 'face_89_x', 'face_89_y', 'face_89_z', 'face_90_x', 'face_90_y', 'face_90_z', 'face_91_x', 'face_91_y', 'face_91_z', 'face_92_x', 'face_92_y', 'face_92_z', 'face_93_x', 'face_93_y', 'face_93_z', 'face_94_x', 'face_94_y', 'face_94_z', 'face_95_x', 'face_95_y', 'face_95_z', 'face_96_x', 'face_96_y', 'face_96_z', 'face_97_x', 'face_97_y', 'face_97_z', 'face_98_x', 'face_98_y', 'face_98_z', 'face_99_x', 'face_99_y', 'face_99_z', 'face_100_x', 'face_100_y', 'face_100_z', 'face_101_x', 'face_101_y', 'face_101_z', 'face_102_x', 'face_102_y', 'face_102_z', 'face_103_x', 'face_103_y', 'face_103_z', 'face_104_x', 'face_104_y', 'face_104_z', 'face_105_x', 'face_105_y', 'face_105_z', 'face_106_x', 'face_106_y', 'face_106_z', 'face_107_x', 'face_107_y', 'face_107_z', 'face_108_x', 'face_108_y', 'face_108_z', 'face_109_x', 'face_109_y', 'face_109_z', 'face_110_x', 'face_110_y', 'face_110_z', 'face_111_x', 'face_111_y', 'face_111_z', 'face_112_x', 'face_112_y', 'face_112_z', 'face_113_x', 'face_113_y', 'face_113_z', 'face_114_x', 'face_114_y', 'face_114_z', 'face_115_x', 'face_115_y', 'face_115_z', 'face_116_x', 'face_116_y', 'face_116_z', 'face_117_x', 'face_117_y', 'face_117_z', 'face_118_x', 'face_118_y', 'face_118_z', 'face_119_x', 'face_119_y', 'face_119_z', 'face_120_x', 'face_120_y', 'face_120_z', 'face_121_x', 'face_121_y', 'face_121_z', 'face_122_x', 'face_122_y', 'face_122_z', 'face_123_x', 'face_123_y', 'face_123_z', 'face_124_x', 'face_124_y', 'face_124_z', 'face_125_x', 'face_125_y', 'face_125_z', 'face_126_x', 'face_126_y', 'face_126_z', 'face_127_x', 'face_127_y', 'face_127_z', 'face_128_x', 'face_128_y', 'face_128_z', 'face_129_x', 'face_129_y', 'face_129_z', 'face_130_x', 'face_130_y', 'face_130_z', 'face_131_x', 'face_131_y', 'face_131_z', 'face_132_x', 'face_132_y', 'face_132_z', 'face_133_x', 'face_133_y', 'face_133_z', 'face_134_x', 'face_134_y', 'face_134_z', 'face_135_x', 'face_135_y', 'face_135_z', 'face_136_x', 'face_136_y', 'face_136_z', 'face_137_x', 'face_137_y', 'face_137_z', 'face_138_x', 'face_138_y', 'face_138_z', 'face_139_x', 'face_139_y', 'face_139_z', 'face_140_x', 'face_140_y', 'face_140_z', 'face_141_x', 'face_141_y', 'face_141_z', 'face_142_x', 'face_142_y', 'face_142_z', 'face_143_x', 'face_143_y', 'face_143_z', 'face_144_x', 'face_144_y', 'face_144_z', 'face_145_x', 'face_145_y', 'face_145_z', 'face_146_x', 'face_146_y', 'face_146_z', 'face_147_x', 'face_147_y', 'face_147_z', 'face_148_x', 'face_148_y', 'face_148_z', 'face_149_x', 'face_149_y', 'face_149_z', 'face_150_x', 'face_150_y', 'face_150_z', 'face_151_x', 'face_151_y', 'face_151_z', 'face_152_x', 'face_152_y', 'face_152_z', 'face_153_x', 'face_153_y', 'face_153_z', 'face_154_x', 'face_154_y', 'face_154_z', 'face_155_x', 'face_155_y', 'face_155_z', 'face_156_x', 'face_156_y', 'face_156_z', 'face_157_x', 'face_157_y', 'face_157_z', 'face_158_x', 'face_158_y', 'face_158_z', 'face_159_x', 'face_159_y', 'face_159_z', 'face_160_x', 'face_160_y', 'face_160_z', 'face_161_x', 'face_161_y', 'face_161_z', 'face_162_x', 'face_162_y', 'face_162_z', 'face_163_x', 'face_163_y', 'face_163_z', 'face_164_x', 'face_164_y', 'face_164_z', 'face_165_x', 'face_165_y', 'face_165_z', 'face_166_x', 'face_166_y', 'face_166_z', 'face_167_x', 'face_167_y', 'face_167_z', 'face_168_x', 'face_168_y', 'face_168_z', 'face_169_x', 'face_169_y', 'face_169_z', 'face_170_x', 'face_170_y', 'face_170_z', 'face_171_x', 'face_171_y', 'face_171_z', 'face_172_x', 'face_172_y', 'face_172_z', 'face_173_x', 'face_173_y', 'face_173_z', 'face_174_x', 'face_174_y', 'face_174_z', 'face_175_x', 'face_175_y', 'face_175_z', 'face_176_x', 'face_176_y', 'face_176_z', 'face_177_x', 'face_177_y', 'face_177_z', 'face_178_x', 'face_178_y', 'face_178_z', 'face_179_x', 'face_179_y', 'face_179_z', 'face_180_x', 'face_180_y', 'face_180_z', 'face_181_x', 'face_181_y', 'face_181_z', 'face_182_x', 'face_182_y', 'face_182_z', 'face_183_x', 'face_183_y', 'face_183_z', 'face_184_x', 'face_184_y', 'face_184_z', 'face_185_x', 'face_185_y', 'face_185_z', 'face_186_x', 'face_186_y', 'face_186_z', 'face_187_x', 'face_187_y', 'face_187_z', 'face_188_x', 'face_188_y', 'face_188_z', 'face_189_x', 'face_189_y', 'face_189_z', 'face_190_x', 'face_190_y', 'face_190_z', 'face_191_x', 'face_191_y', 'face_191_z', 'face_192_x', 'face_192_y', 'face_192_z', 'face_193_x', 'face_193_y', 'face_193_z', 'face_194_x', 'face_194_y', 'face_194_z', 'face_195_x', 'face_195_y', 'face_195_z', 'face_196_x', 'face_196_y', 'face_196_z', 'face_197_x', 'face_197_y', 'face_197_z', 'face_198_x', 'face_198_y', 'face_198_z', 'face_199_x', 'face_199_y', 'face_199_z', 'face_200_x', 'face_200_y', 'face_200_z', 'face_201_x', 'face_201_y', 'face_201_z', 'face_202_x', 'face_202_y', 'face_202_z', 'face_203_x', 'face_203_y', 'face_203_z', 'face_204_x', 'face_204_y', 'face_204_z', 'face_205_x', 'face_205_y', 'face_205_z', 'face_206_x', 'face_206_y', 'face_206_z', 'face_207_x', 'face_207_y', 'face_207_z', 'face_208_x', 'face_208_y', 'face_208_z', 'face_209_x', 'face_209_y', 'face_209_z', 'face_210_x', 'face_210_y', 'face_210_z', 'face_211_x', 'face_211_y', 'face_211_z', 'face_212_x', 'face_212_y', 'face_212_z', 'face_213_x', 'face_213_y', 'face_213_z', 'face_214_x', 'face_214_y', 'face_214_z', 'face_215_x', 'face_215_y', 'face_215_z', 'face_216_x', 'face_216_y', 'face_216_z', 'face_217_x', 'face_217_y', 'face_217_z', 'face_218_x', 'face_218_y', 'face_218_z', 'face_219_x', 'face_219_y', 'face_219_z', 'face_220_x', 'face_220_y', 'face_220_z', 'face_221_x', 'face_221_y', 'face_221_z', 'face_222_x', 'face_222_y', 'face_222_z', 'face_223_x', 'face_223_y', 'face_223_z', 'face_224_x', 'face_224_y', 'face_224_z', 'face_225_x', 'face_225_y', 'face_225_z', 'face_226_x', 'face_226_y', 'face_226_z', 'face_227_x', 'face_227_y', 'face_227_z', 'face_228_x', 'face_228_y', 'face_228_z', 'face_229_x', 'face_229_y', 'face_229_z', 'face_230_x', 'face_230_y', 'face_230_z', 'face_231_x', 'face_231_y', 'face_231_z', 'face_232_x', 'face_232_y', 'face_232_z', 'face_233_x', 'face_233_y', 'face_233_z', 'face_234_x', 'face_234_y', 'face_234_z', 'face_235_x', 'face_235_y', 'face_235_z', 'face_236_x', 'face_236_y', 'face_236_z', 'face_237_x', 'face_237_y', 'face_237_z', 'face_238_x', 'face_238_y', 'face_238_z', 'face_239_x', 'face_239_y', 'face_239_z', 'face_240_x', 'face_240_y', 'face_240_z', 'face_241_x', 'face_241_y', 'face_241_z', 'face_242_x', 'face_242_y', 'face_242_z', 'face_243_x', 'face_243_y', 'face_243_z', 'face_244_x', 'face_244_y', 'face_244_z', 'face_245_x', 'face_245_y', 'face_245_z', 'face_246_x', 'face_246_y', 'face_246_z', 'face_247_x', 'face_247_y', 'face_247_z', 'face_248_x', 'face_248_y', 'face_248_z', 'face_249_x', 'face_249_y', 'face_249_z', 'face_250_x', 'face_250_y', 'face_250_z', 'face_251_x', 'face_251_y', 'face_251_z', 'face_252_x', 'face_252_y', 'face_252_z', 'face_253_x', 'face_253_y', 'face_253_z', 'face_254_x', 'face_254_y', 'face_254_z', 'face_255_x', 'face_255_y', 'face_255_z', 'face_256_x', 'face_256_y', 'face_256_z', 'face_257_x', 'face_257_y', 'face_257_z', 'face_258_x', 'face_258_y', 'face_258_z', 'face_259_x', 'face_259_y', 'face_259_z', 'face_260_x', 'face_260_y', 'face_260_z', 'face_261_x', 'face_261_y', 'face_261_z', 'face_262_x', 'face_262_y', 'face_262_z', 'face_263_x', 'face_263_y', 'face_263_z', 'face_264_x', 'face_264_y', 'face_264_z', 'face_265_x', 'face_265_y', 'face_265_z', 'face_266_x', 'face_266_y', 'face_266_z', 'face_267_x', 'face_267_y', 'face_267_z', 'face_268_x', 'face_268_y', 'face_268_z', 'face_269_x', 'face_269_y', 'face_269_z', 'face_270_x', 'face_270_y', 'face_270_z', 'face_271_x', 'face_271_y', 'face_271_z', 'face_272_x', 'face_272_y', 'face_272_z', 'face_273_x', 'face_273_y', 'face_273_z', 'face_274_x', 'face_274_y', 'face_274_z', 'face_275_x', 'face_275_y', 'face_275_z', 'face_276_x', 'face_276_y', 'face_276_z', 'face_277_x', 'face_277_y', 'face_277_z', 'face_278_x', 'face_278_y', 'face_278_z', 'face_279_x', 'face_279_y', 'face_279_z', 'face_280_x', 'face_280_y', 'face_280_z', 'face_281_x', 'face_281_y', 'face_281_z', 'face_282_x', 'face_282_y', 'face_282_z', 'face_283_x', 'face_283_y', 'face_283_z', 'face_284_x', 'face_284_y', 'face_284_z', 'face_285_x', 'face_285_y', 'face_285_z', 'face_286_x', 'face_286_y', 'face_286_z', 'face_287_x', 'face_287_y', 'face_287_z', 'face_288_x', 'face_288_y', 'face_288_z', 'face_289_x', 'face_289_y', 'face_289_z', 'face_290_x', 'face_290_y', 'face_290_z', 'face_291_x', 'face_291_y', 'face_291_z', 'face_292_x', 'face_292_y', 'face_292_z', 'face_293_x', 'face_293_y', 'face_293_z', 'face_294_x', 'face_294_y', 'face_294_z', 'face_295_x', 'face_295_y', 'face_295_z', 'face_296_x', 'face_296_y', 'face_296_z', 'face_297_x', 'face_297_y', 'face_297_z', 'face_298_x', 'face_298_y', 'face_298_z', 'face_299_x', 'face_299_y', 'face_299_z', 'face_300_x', 'face_300_y', 'face_300_z', 'face_301_x', 'face_301_y', 'face_301_z', 'face_302_x', 'face_302_y', 'face_302_z', 'face_303_x', 'face_303_y', 'face_303_z', 'face_304_x', 'face_304_y', 'face_304_z', 'face_305_x', 'face_305_y', 'face_305_z', 'face_306_x', 'face_306_y', 'face_306_z', 'face_307_x', 'face_307_y', 'face_307_z', 'face_308_x', 'face_308_y', 'face_308_z', 'face_309_x', 'face_309_y', 'face_309_z', 'face_310_x', 'face_310_y', 'face_310_z', 'face_311_x', 'face_311_y', 'face_311_z', 'face_312_x', 'face_312_y', 'face_312_z', 'face_313_x', 'face_313_y', 'face_313_z', 'face_314_x', 'face_314_y', 'face_314_z', 'face_315_x', 'face_315_y', 'face_315_z', 'face_316_x', 'face_316_y', 'face_316_z', 'face_317_x', 'face_317_y', 'face_317_z', 'face_318_x', 'face_318_y', 'face_318_z', 'face_319_x', 'face_319_y', 'face_319_z', 'face_320_x', 'face_320_y', 'face_320_z', 'face_321_x', 'face_321_y', 'face_321_z', 'face_322_x', 'face_322_y', 'face_322_z', 'face_323_x', 'face_323_y', 'face_323_z', 'face_324_x', 'face_324_y', 'face_324_z', 'face_325_x', 'face_325_y', 'face_325_z', 'face_326_x', 'face_326_y', 'face_326_z', 'face_327_x', 'face_327_y', 'face_327_z', 'face_328_x', 'face_328_y', 'face_328_z', 'face_329_x', 'face_329_y', 'face_329_z', 'face_330_x', 'face_330_y', 'face_330_z', 'face_331_x', 'face_331_y', 'face_331_z', 'face_332_x', 'face_332_y', 'face_332_z', 'face_333_x', 'face_333_y', 'face_333_z', 'face_334_x', 'face_334_y', 'face_334_z', 'face_335_x', 'face_335_y', 'face_335_z', 'face_336_x', 'face_336_y', 'face_336_z', 'face_337_x', 'face_337_y', 'face_337_z', 'face_338_x', 'face_338_y', 'face_338_z', 'face_339_x', 'face_339_y', 'face_339_z', 'face_340_x', 'face_340_y', 'face_340_z', 'face_341_x', 'face_341_y', 'face_341_z', 'face_342_x', 'face_342_y', 'face_342_z', 'face_343_x', 'face_343_y', 'face_343_z', 'face_344_x', 'face_344_y', 'face_344_z', 'face_345_x', 'face_345_y', 'face_345_z', 'face_346_x', 'face_346_y', 'face_346_z', 'face_347_x', 'face_347_y', 'face_347_z', 'face_348_x', 'face_348_y', 'face_348_z', 'face_349_x', 'face_349_y', 'face_349_z', 'face_350_x', 'face_350_y', 'face_350_z', 'face_351_x', 'face_351_y', 'face_351_z', 'face_352_x', 'face_352_y', 'face_352_z', 'face_353_x', 'face_353_y', 'face_353_z', 'face_354_x', 'face_354_y', 'face_354_z', 'face_355_x', 'face_355_y', 'face_355_z', 'face_356_x', 'face_356_y', 'face_356_z', 'face_357_x', 'face_357_y', 'face_357_z', 'face_358_x', 'face_358_y', 'face_358_z', 'face_359_x', 'face_359_y', 'face_359_z', 'face_360_x', 'face_360_y', 'face_360_z', 'face_361_x', 'face_361_y', 'face_361_z', 'face_362_x', 'face_362_y', 'face_362_z', 'face_363_x', 'face_363_y', 'face_363_z', 'face_364_x', 'face_364_y', 'face_364_z', 'face_365_x', 'face_365_y', 'face_365_z', 'face_366_x', 'face_366_y', 'face_366_z', 'face_367_x', 'face_367_y', 'face_367_z', 'face_368_x', 'face_368_y', 'face_368_z', 'face_369_x', 'face_369_y', 'face_369_z', 'face_370_x', 'face_370_y', 'face_370_z', 'face_371_x', 'face_371_y', 'face_371_z', 'face_372_x', 'face_372_y', 'face_372_z', 'face_373_x', 'face_373_y', 'face_373_z', 'face_374_x', 'face_374_y', 'face_374_z', 'face_375_x', 'face_375_y', 'face_375_z', 'face_376_x', 'face_376_y', 'face_376_z', 'face_377_x', 'face_377_y', 'face_377_z', 'face_378_x', 'face_378_y', 'face_378_z', 'face_379_x', 'face_379_y', 'face_379_z', 'face_380_x', 'face_380_y', 'face_380_z', 'face_381_x', 'face_381_y', 'face_381_z', 'face_382_x', 'face_382_y', 'face_382_z', 'face_383_x', 'face_383_y', 'face_383_z', 'face_384_x', 'face_384_y', 'face_384_z', 'face_385_x', 'face_385_y', 'face_385_z', 'face_386_x', 'face_386_y', 'face_386_z', 'face_387_x', 'face_387_y', 'face_387_z', 'face_388_x', 'face_388_y', 'face_388_z', 'face_389_x', 'face_389_y', 'face_389_z', 'face_390_x', 'face_390_y', 'face_390_z', 'face_391_x', 'face_391_y', 'face_391_z', 'face_392_x', 'face_392_y', 'face_392_z', 'face_393_x', 'face_393_y', 'face_393_z', 'face_394_x', 'face_394_y', 'face_394_z', 'face_395_x', 'face_395_y', 'face_395_z', 'face_396_x', 'face_396_y', 'face_396_z', 'face_397_x', 'face_397_y', 'face_397_z', 'face_398_x', 'face_398_y', 'face_398_z', 'face_399_x', 'face_399_y', 'face_399_z', 'face_400_x', 'face_400_y', 'face_400_z', 'face_401_x', 'face_401_y', 'face_401_z', 'face_402_x', 'face_402_y', 'face_402_z', 'face_403_x', 'face_403_y', 'face_403_z', 'face_404_x', 'face_404_y', 'face_404_z', 'face_405_x', 'face_405_y', 'face_405_z', 'face_406_x', 'face_406_y', 'face_406_z', 'face_407_x', 'face_407_y', 'face_